events{}
http
{
    error_log /var/log/nginx/error.log warn;
    server {
        listen      443 ssl;
        server_name jsanger.42.fr;
        root    /var/www/html;
        index index.php;
        ssl_certificate     /etc/nginx/ssl/jsanger.42.fr.crt;
        ssl_certificate_key /etc/nginx/ssl/jsanger.42.fr.key;
        ssl_protocols       TLSv1.2;
        ssl_session_timeout 10m;
        keepalive_timeout 70;

        # WordPress
        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }

        # Adminer
        location /adminer/ {
            rewrite ^/adminer/(.*)$ /adminer.php break;
            proxy_pass http://adminer:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Backend API
        location /api/ {
            proxy_pass http://backend:5000/;
            proxy_set_header Host $host;
        }

        # Website
        location /web/ {
            proxy_pass http://website:80/;
            proxy_set_header Host $host;
        }
    }
}

# https://jsanger.42.fr/          WordPress
# https://jsanger.42.fr/adminer/  Adminer
# https://jsanger.42.fr/api/      Backend API
# https://jsanger.42.fr/web/      Website