services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - '443:443'
      - '8080:8080'
      - '4242:4242'
    restart: on-failure
    depends_on:
      - wordpress
    volumes:
      - wordpress-volume:/var/www/html
    networks:
      - inception-net
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis
    volumes:
      - wordpress-volume:/var/www/html
    networks:
      - inception-net
    restart: on-failure

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - inception-net
    ports:
      - "3306:3306"

  adminer:
    container_name: adminer
    build:
      context: ./requirements/adminer
    depends_on:
      - mariadb
    restart: on-failure
    networks:
      - inception-net
  
  ftp:
    container_name: ftp
    build:
      context: ./requirements/ftp
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    env_file:
      - .env
    volumes:
      - wordpress-volume:/var/www/html
    networks:
      - inception-net
    restart: on-failure

  website:
    container_name: website
    build:
      context: ./requirements/website
    networks:
      - inception-net
    restart: on-failure

  redis:
    container_name: redis
    build:
      context: ./requirements/redis
    networks:
      - inception-net
    restart: on-failure

  backend:
    container_name: backend
    build:
      context: ./requirements/backend
    ports:
      - "5000:5000"
    networks:
      - inception-net
    restart: on-failure








volumes:
  wordpress-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/data/wordpress
  mariadb-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/data/mariadb

    






networks:
  inception-net:
    driver: bridge
    name: inception


